# https://docs.pytest.org/en/stable/customize.html
[tool.pytest.ini_options]
addopts = "--alluredir allure-results"
markers = [
    "create_booking",
    "delete_booking",
    "get_booking",
    "get_booking_ids",
    "patch_booking",
    "put_booking"
    ]

log_file = "log_tests.txt"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s - %(name)s - [%(levelname)8s] %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
